# Generated by Django 3.2.5 on 2023-01-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kannada_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='book_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='uname',
            field=models.CharField(max_length=50),
        ),
    ]
