# Generated by Django 3.2.5 on 2023-01-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kannada_books', '0002_auto_20230101_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
